
language: scala

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom

matrix:
  include:
  - jdk: oraclejdk8
    scala: 2.12.3
  - jdk: oraclejdk8
    scala: 2.11.11

script:
 - sbt ++$TRAVIS_SCALA_VERSION -J-Xmx3G test

