
dist: xenial
language: scala

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom

# Unfortunately, a JDK 8 is missing here (this project must work on JDK 8)

matrix:
  include:
  - jdk: openjdk11
    scala: 2.12.12
  - jdk: openjdk9
    scala: 2.13.3
  - jdk: openjdk11
    scala: 2.13.3

script:
 - sbt ++$TRAVIS_SCALA_VERSION -J-Xmx3G clean test checkDuplicates

